import { Footer, Navbar } from "@/components";
import "./globals.css";
import Head from "next/head";
import { StateContext } from "@/context/stateContext";
import { Toaster } from "react-hot-toast";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Perry Luscious",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateContext>
          <div className="layout">
            <Toaster />
            <Head>
              <title>Perry Luscious</title>
            </Head>
            <header>
              <Navbar />
            </header>
            <main className="main-container">{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </StateContext>
      </body>
    </html>
  );
}
